### ISSUE TITLE
Hi! I have a little problem.

### ISSUE THREAD

**Issue by xhzengAIB** [coffellas-cto/GDWebViewController#1]
@coffellas-cto 
Hi! 
Thank you for your open source libraries.

Hi! I have a little problem:
How did the Supports the back - forward swipe gestures of? Where is the principle?

Jack

**Comment by coffellas-cto** [comment]
Hi,
can you please clarify your question/issue?

The usage should be simple - just set the `allowsBackForwardNavigationGestures` property of `GDWebViewController` instance to `true` or back to `false` if not needed any longer.

**Comment by xhzengAIB** [comment]
Hi！
Yet, got it, this API is iOS8 SDK, is not compatible with other SDK.
Thank you.

Jack
