### ISSUE TITLE
Is this accepted on App Store?

### ISSUE THREAD

**Issue by tiagopotencia** [coffellas-cto/GDWebViewController#21]
Hi! First, congrats for the initiative!
I just need a webview on my IOS app, what's the chances to use GD ViewController on my app to display my webpage and the be accepted on app store?

Thanks!

**Comment by coffellas-cto** [comment]
The problem might be not with `GDViewController` but with your app features. If it's just web page with no additional functionality Apple's review team might decline the app.

See https://developer.apple.com/app-store/review/guidelines/
