### ISSUE TITLE
Resource could not be loaded due to App Transport security

### ISSUE THREAD

**Issue by edudemy** [coffellas-cto/GDWebViewController#22]
Got the following error(pic attached) on replacing the gHost url and running in the simulator.

"Error: Resource could not be loaded because the App Transport security policy requires the use of a secure connection." 

What changes are to be made to to get this going with unsecured websites or for redirects example: "edudemy.github.com" ? TIA
 
![image](https://cloud.githubusercontent.com/assets/2371533/21072116/c30dd4e4-bedd-11e6-8d63-a930d06666da.png)

**Comment by coffellas-cto** [comment]
It has nothing to do with `GDWebViewController`, I suppose. If you are using non-https site, you have to disable app transport security in general or for a particular web site.

Add a key to your Info.plist to disable ATS
```<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

Or dig deeper into this topic here:
https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33

Or google "disable app transport security for iOS" :)

**Comment by zeshanshani** [comment]
This solution may work if anyone still face issue: https://github.com/coffellas-cto/GDWebViewController/issues/7#issuecomment-384393504
