### ISSUE TITLE
xCode 6.3.1 Compile issue 

### ISSUE THREAD

**Issue by hcsylvest** [coffellas-cto/GDWebViewController#3]
This part will not build.  When using xCode version 6.3.1
override init() {
        super.init()
        webView = WKWebView()
        webView.navigationDelegate = self
        webView.setTranslatesAutoresizingMaskIntoConstraints(false)
        
        toolbarContainer = GDWebViewNavigationToolbar(delegate: self)
        toolbarContainer.setTranslatesAutoresizingMaskIntoConstraints(false)
    } 
and
func webViewController(webViewController: GDWebViewController, didChangeTitle newTitle: NSString?) {
        navVC.navigationBar.topItem?.title = newTitle
    }

**Comment by coffellas-cto** [comment]
Will be changed soon

**Comment by coffellas-cto** [comment]
Please check if commit 6ba07a5d2ce1d1e950f53ccb10242427c799481a fixes your issues

**Comment by animaonline** [comment]
@coffellas-cto Hi, it still does´t work, init is never executed.

**Comment by coffellas-cto** [comment]
How do you instantiate the GDWebViewController instance? Because programmatically it is created without any problems.
And the
```swift
required init(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
```
is there.
*Xcode Version 6.3.1, Swift 1.2*

**Comment by animaonline** [comment]
From the storyboard.

On Friday, May 15, 2015, Alex Gordiyenko <notifications@github.com> wrote:

> How do you instantiate the GDWebViewController instance? Because
> programmatically it is created without any problems.
> And the
>
> required init(coder aDecoder: NSCoder) {
>         super.init(coder: aDecoder)
>     }
>
> is there.
> *Xcode Version 6.3.1, Swift 1.2*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coffellas-cto/GDWebViewController/issues/3#issuecomment-102526973>
> .
>


-- 
Roman Alifanov - MCAD - MCTS - MCP - MCT
http://www.animaonline.com

**Comment by coffellas-cto** [comment]
Fixed
