### ISSUE TITLE
allowsBackForwardNavigationGestures doesn't work time from time

### ISSUE THREAD

**Issue by animaonline** [coffellas-cto/GDWebViewController#4]
Steps to reproduce:

Push the WebViewController from a Nav controller (For example when a button is clicked).
Navigate a couple of links
Go back to nav root
Open the WebViewController again
Navigate a couple of links
Try swiping back

It goes back to the nav root ignoring previously navigated links.

Have you observed that before?

**Comment by coffellas-cto** [comment]
I have reproduced this issue several times.
Looks like it's interfering with navController's `interactivePopGestureRecognizer `.

Please check if commit 2516819df5 fixes that

**Comment by VictorShurapov** [comment]
Hello! Could you please explain how to fix this issue when you have allowsbackforwardnavigationgestures with wkwebview inside navController? :-)
