### ISSUE TITLE
Javascript alerts

### ISSUE THREAD

**Issue by digitalprecision** [coffellas-cto/GDWebViewController#6]
Modals seem to work fine, but I can't get native JS alerts to render, any ideas?

**Comment by coffellas-cto** [comment]
Hello. Can you please be more specific about the issue you are facing? Like steps to reproduce. thanks.

**Comment by digitalprecision** [comment]
I have a webview that does something like:

<script type="text/javascript">
alert("hello");
</script>

But it's not working through your framework.  More info @ http://stackoverflow.com/questions/34185339/wkwebview-javascript-confirm-and-alert-not-working

**Comment by FarhadMammadli** [comment]
Digitalprecision how did you use js on webview? I also need to load javascipt

**Comment by digitalprecision** [comment]
We ended up using this code, as we didn't have time to debug: https://github.com/coffellas-cto/GDWebViewController

**Comment by coffellas-cto** [comment]
@digitalprecision Which code exactly? You've added a link to the root of the source :)

**Comment by FarhadMammadli** [comment]
@coffellas-cto can you answer my question as well?

**Comment by digitalprecision** [comment]
@coffellas-cto lol sorry, was early in the morning when I responded. I remember what I had to do now. Instead of using native js alerts/confirms we implemented Bootbox (http://bootboxjs.com/) api to render our dialog boxes instead. 

And, actually, we still have an issue with our app where we cannot open facebook/twitter dialogs when a user wants to share a !shouttag, so if a solution arises we would definitely implement asap.

**Comment by coffellas-cto** [comment]
@digitalprecision  Please refer to release v1.2. https://github.com/coffellas-cto/GDWebViewController/releases/tag/v1.2
Let me know if this fixes your issue.

See `AppDelegate.swift` file and global variable `let gShowAlertOnDidFinishLoading = false`. Change it to `true` and delegate method `webViewController(webViewController: GDWebViewController, didFinishLoading loadedURL: NSURL?)` starts injecting JS alerts.
