### ISSUE TITLE
How to load a website?

### ISSUE THREAD

**Issue by FarhadMammadli** [coffellas-cto/GDWebViewController#7]
How to load a website? it only loads apple.com. when i change url, it says connection is prohibited

**Comment by coffellas-cto** [comment]
Please carefully examine `AppDelegate.swift` file. 
There is a line `let gHost = "apple.com"`. And inside `func webViewController(webViewController: GDWebViewController, decidePolicyForNavigationAction navigationAction: WKNavigationAction, decisionHandler: (WKNavigationActionPolicy) -> Void)` there is a check if a domain is the same. Just don't implement this method in your project and the restriction won't take place.

This restriction was included for presentation purposes only.

**Comment by zeshanshani** [comment]
It didn't work for me @coffellas-cto unfortunately. However, this solution worked: https://stackoverflow.com/a/32631185 😃 

This was the complete code I had to add to the `Info.plist` file:

```
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSExceptionDomains</key>
	<dict>
		<key>domain.com</key>
		<dict>
			<key>NSExceptionAllowsInsecureHTTPLoads</key>
			<true/>
			<key>NSIncludesSubdomains</key>
			<true/>
			<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
			<false/>
		</dict>
	</dict>
</dict>
```

It's a combination of these two Stackoverflow answers: 

https://stackoverflow.com/a/32631185 & https://stackoverflow.com/a/33306373
