### ISSUE TITLE
How can i inject javascript code into webview?

### ISSUE THREAD

**Issue by FarhadMammadli** [coffellas-cto/GDWebViewController#8]
How can i inject javascript code into webview when page finished loading? I cannot find function webviewdidFinished. Can you help me how to implement ?

**Comment by FarhadMammadli** [comment]
You did not wrote this code by yourself ? -_-

**Comment by coffellas-cto** [comment]
@FarhadMammadli 
Release v1.2 adds this functionality. https://github.com/coffellas-cto/GDWebViewController/releases/tag/v1.2

See `AppDelegate.swift` (GDWebBrowserClient example project) and global variable `let gShowAlertOnDidFinishLoading = false`. Change it to `true` and delegate method `webViewController(webViewController: GDWebViewController, didFinishLoading loadedURL: NSURL?)` starts injecting JS alerts.

**Comment by FarhadMammadli** [comment]
thanks a lot! i appreciate this
